version: '3.7'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - 5001:5000
    environment:
      - FLASK_APP=server/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=server.config.DevelopmentConfig